# Site settings
title: Siddharth Sharma
description: Siddharth's CV
favicon: /assets/img/avatar.JPG
baseurl: https://ddbullfrog.github.io/resumecard
url: https://ddbullfrog.github.io/resumecard
rss_url: /pages/atom.xml
google_analytics: UA-63653234-1

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: Siddharth Sharma
  title: Java Developer
  address: London, United Kingdom
  email: sid.sharma9@outlook.com
  #link: http://ddbullfrog.com
  #weibo:
  github: https://github.com/siddharth0929
  linkedin: https://www.linkedin.com/in/siddharthsharma0909
  #twitter: ddbullfrog
  gavatar: /resumecard/assets/img/avatar.JPG
  stackoverflow:
#  stackoverflow: 4582127
  workHistory:
    - work1:
      company: XXX Ltd
      location: Auckland, New Zealand
      title: Java Developer

  educationHistory:
    - education1:
      organization: Birmingham City University
      location: Birmingham, United Kingdom
      degree: Masters
      major: Computer Science
      started: 2023
      duration: (2023 - 2024)
      description: 
      education2:
      organization: DAVV University
      location: Indore, India
      degree: Bachelor
      major: Computer Applications
      started: 2019
      duration: (2019 - 2022)
      description: 
  languages:
    - language1:
      name: English
      proficiency: Professional
    - language2:
      name: Hindi
      proficiency: Native
  programmingSkills:
    - skill1:
      name: Python
      percentage: 70%
    - skill2:
      name: HTML
      percentage: 100%
    - skill3:
      name: MySQL
      percentage: 70%
    - skill4:
      name: MsOffice
      percentage: 100%
    - skill5:
      name: Github 
      percentage: 90%
    skill6:
      name: Docker
      percentage: 60%  
